### ISSUE TITLE
Error 2

### ISSUE THREAD

**Issue by ghost** [DistilledLtd/heimdall#2]
Hi, i tried to use your script but it gives the following error:

Traceback (most recent call last):
  File "takescreenshots.py", line 3, in <module>
    heimdall.png("https://www.medieval-europe.eu/", device="Laptop")
  File "/usr/lib/python2.7/site-packages/heimdall/heimdall.py", line 33, in png
    return save(url, **kwargs)
  File "/usr/lib/python2.7/site-packages/heimdall/heimdall.py", line 22, in save
    screenshot_image = screenshot(url, **kwargs)
  File "/usr/lib/python2.7/site-packages/heimdall/heimdall.py", line 86, in screenshot
    stdout=subprocess.PIPE).communicate()[0]
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Can you help me in finding out what's wrong?

**Comment by ghost** [comment]
Problem solved, (wrong installation of phantomJs)
